"""
base_simulation.py - Common simulation class

Copyright 2026 - Christopher T Niessl

See LICENSE.txt for usage.
"""

from datetime import datetime, UTC

from base_masim_types import some_action_stub, some_agent, some_log, some_sim

# TODO: Inherit basic sim type signature
class base_simulation(some_sim):
    """Base simulation.""" 
    
    def __init__(self, sim_name: str) -> None:
        """Initialize the simulation."""
        self.active_agents: dict[some_agent] = {}
        self.inactive_agaents: dict[some_agent] = {}
        self.sim_act_history: list[some_log] = []
        self.sim_name: str = sim_name
        self.sim_step: int = 0

    def advance_step(self) -> None:
        """Perform a timestep in the simulation."""
        action_list: list[some_action_stub] = []
        self.setup_phase()
        for agent in self.agents:
            action_list.append(agent.plan_action())
        for action in action_list:
            self.apply_action(action)
        self.end_phase()
        self.cleanup()
        self.sim_step += 1
    
    def add_agent(self, agent_to_add: some_agent) -> None:
        """Add an agent to the active agents."""
        self._sim_act_history.append(self._gen_add_history_stub(agent_to_add))
        # TODO: Add check if the agent already exists with that name
        self.active_agents[agent_to_add.agent_id] = agent_to_add
    
    def _gen_deact_history_stub(self, agent_to_deact: some_agent) -> None:
    	"""Add the move to inactive for an agent in the log."""
    	raise NotImplementedError
    
    def _gen_add_history_stub(self, agent_to_add: some_agent) -> None:
        """Add the addition of an agent in the log."""
        raise NotImplementedError
    
    def deactivate_agent(self, agent_to_deact: str) -> None:
        """Move an agent from active agents to inactive."""
        target_agent = self.agents.pop(agent_to_deact, None)
        self.sim_act_history.append(self._gen_deact_history_stub(target_agent))
        self.inactive_agents[agent_to_deact] = target_agent
    
    def cleanup(self) -> None:
        """Remove deactivated agents from the simulation."""
        for agent_key in self.agents.keys():
            target_agent = self.agents[agent_key]
            if not agent.active:
                self.deactivate_agent(agent_key)

    def get_step(self) -> int:
        """Return the current simulation step."""
        return self.sim_step
   
    def setup_phase(self) -> None:
        """Check global conditions and modify them here."""
        raise NotImplementedError
    
    def end_phase(self) -> None:
        """Resolve any agents or other conditions before next setup."""
        raise NotImplementedError
        
    def apply_action(self, action: some_action_stub) -> None:
        """Run the action generated by the agent."""
        log_stub: some_log = action.apply(self, datetime.now(UTC))
        agent_init: some_agent = self.agents[action.initiator_id]
        agent_other: some_agent = self.agents[action.target]
        if agent_init is not None:
            agent_init.add_to_history(log_stub)
        if agent_other is not None:
            agent_other.add_to_history(log_stub)
    
    def dump_full_history_list(self) -> list[some_log_entry]:
        """Dump the full history of the simulation and its agents."""
        return_list: list[some_log] = self.sim_act_history
        active_agent_history: list[some_log] = [log_entry for hist_item in agent.history_list for agent in self.active_agents]
        inactive_agent_history: list[some_log] = [log_entry for hist_item in agent.history_list for agent in self.inactive_agents]
        return_list = return_list + active_agent_history + inactive_agent_history
        
        return return_list.sort()
