"""
base_simulation.py - Common simulation class

Copyright 2026 - Christopher T Niessl

See LICENSE.txt for usage.
"""

from base_masim_types import some_action_stub, some_agent, some_sim

# TODO: Inherit basic sim type signature
class base_simulation(some_sim):
    """Base simulation.""" 
    
    def __init__(self) -> None:
        """Initialize the simulation."""
        self.agents: dict[some_agent] = {}
        self.sim_step: int = 0

    def step(self) -> None:
        """Perform a timestep in the simulation."""
        action_list: list[some_action_stub] = []
        self.setup_phase()
        for agent in self.agents:
            action_list.append(agent.plan_action())
        for action in action_list:
            self.apply_action(action)
        self.end_phase()
        self.sim_step += 1
   
    def setup_phase(self) -> None:
        """Check global conditions and modify them here."""
        raise NotImplementedError
    
    def end_phase(self) -> None:
        """Resolve any agents or other conditions before next setup."""
        raise NotImplementedError
        
    def apply_action(self, action: some_action_stub):
        """Run the action generated by the agent."""
        _ = action.apply(self)
        # TODO: Add log entry to relevant agents
        raise NotImplementedError
