"""
Base_Simulation.py - Common simulation class

Copyright 2026 - Christopher T Niessl

See LICENSE.txt for usage.
"""

class base_simulation:
    """Base simulation.""" 
    
    def __init__(self) -> None:
        self.agents: dict[base_agent] = {}
        self.sim_step: int = 0
    
    def step(self) -> None:
        action_list: list = []
        self.setup_phase()
        for agent in self.agents:
            action_list.append(agent.plan_action())
        for action in action_list:
            self.apply_action(action)
        self.end_phase()
   
    def setup_phase(self) -> None:
        "Check global conditions and modify them here."
        raise NotImplemented
    
    def end_phase(self) -> None:
        "Resolve any agents or other conditions before next setup."
        raise NotImplemented
        
    def apply_action(self, action: base_action) -> None:
        "Run the action generated by the agent."
        raise NotImplemented
