[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "multiagent-simulations"
version = "2026.5.0"
dependencies = []
requires-python = ">=3.12"
authors = [
  {name = "Christopher T Niessl", email = "cniessl_dev@proton.me"},
]
maintainers = []
description = "Lovely Spam! Wonderful Spam!"
readme = ""
license = "GPL-3.0-or-later"
license-files = ["LICEN[CS]E.*"]
keywords = []
classifiers = [
    "Programming Language :: Python"
]

[project.urls]
Repository = "https://github.com/cniessl-HB/MultiagentSimulations"
