"""
dist_simulation_orch.py - Distributed simulation orchestrator

Copyright 2026 - Christopher T Niessl

See LICENSE.txt for usage.
"""

from pathlib import Path

from basesimlib.base_exceptions import (
    AgentAssignedNoneError,
    AgentNotFoundError,
    DuplicateAgentError,
    DeactivateInactiveAgentError,
)
from basesimlib.base_masim_types import some_action_stub, some_agent, some_log, some_sim
from basesimlib.base_log_entry import base_log_entry

from basedistsimlib.dist_resource import dist_resource

from basedistsimlib.dist_exceptions import (
    SubsimNotFoundError
    SubsimDisconnectedError
)

class base_dist_simulation_orch(some_sim):
    """Base distributed simulation."""

    def __init__(self, sim_name: str, json_config: dict) -> None:
        """Initialize the simulation."""
        super().__init__(sim_name)
        self.subsims = {}
        self._read_network_config(json_config)
        self._connected_to_subsims = False

    def __len__(self) -> int:
        return len(self.active_agents) + len(self.inactive_agents)

    def _read_network_config(self, config_dict: dict) -> None:
        self.sub_agent_net_cfgs = {}
        for key in config_dict:
            new_subsim_cfg = dist_resource(**config_dict[key])
            new_subsim_key = new_subsim_cfg.resc_name
            self.subsims[resc_name] = new_subsim_cfg
    
    def _handshake_with_subsims(self) -> None:
       for resc_name_key in self.subsim_net_cfgs:
           subsim_cfg = self.subsim_net_cfgs[resc_name]
           try:
               did_connect = subsim_cfg.connect()
           except Exception as ex:
               did_connect = False
               if subsim_cfg.require_online:
                   raise ex
       self._connected_to_subsims = True

    def _send_rpc_to_subsim(self, rpc: str, target_subsim: str) -> str:
        if target_subsim not in self.subsims:
            raise SubsimNotFoundError
        subsim = self.subsims[target_subsim]
        if not subsim.is_connected():
            raise SubsimDisconnectedError
        return subsim.send_command(rpc)

    def advance_step(self) -> None:
        """Perform a timestep in the simulation."""
        raise NotImplementedError

    def add_agent(self, agent_to_add: some_agent) -> None:
        """Add an agent to the active agents."""
        raise NotImplementedError

    def _gen_deact_history_stub(self, agent_to_deact: some_agent) -> None:
        """Add the move to inactive for an agent in the log."""
        raise NotImplementedError

    def _gen_add_history_stub(self, agent_to_add: some_agent) -> some_log:
        """Add the addition of an agent in the log."""
        raise NotImplementedError

    def _filter_duplicate_log_events(
        self, logs_to_filter: list[some_log]
    ) -> list[some_log]:
        """Take a sorted list of log events, and check for duplicates."""
        raise NotImplementedError

    def deactivate_agent(self, agent_to_deact: str) -> None:
        """Move an agent from active agents to inactive."""
        raise NotImplementedError

    def cleanup(self) -> None:
        """Remove deactivated agents from the simulation."""
        raise NotImplementedError

    def get_step(self) -> int:
        """Return the current simulation step."""
       raise NotImplementedError

    def setup_phase(self) -> None:
        """Check global conditions and modify them here."""
        pass

    def end_phase(self) -> None:
        """Resolve any agents or other conditions before next setup."""
        pass

    def apply_action(self, action: some_action_stub) -> None:
        """Run the action generated by the agent."""
        raise NotImplementedError

    def dump_sim_history_list(self) -> list[some_log]:
        """Dump the history of simulation events."""
        return self.sim_act_history

    def dump_sim_active_agent_history_list(self) -> list[some_log]:
        """Dump the history of all active agents."""
        raise NotImplementedError

    def dump_sim_inactive_agent_history_list(self) -> list[some_log]:
        """Dump the history of all inactive agents."""
        raise NotImplementedError

    def dump_full_history_list(self) -> list[some_log]:
        """Dump the full history of the sim and active and inactive agents.

        Removes duplicates, so any interactions between agents or the sim are
        only included once.

        """
        combined_list = self.dump_sim_history_list()
        combined_list.extend(self.dump_sim_active_agent_history_list())
        combined_list.extend(self.dump_sim_inactive_agent_history_list())
        combined_list.sort()
        return self._filter_duplicate_log_events(combined_list)
